# Generated by Django 5.0.5 on 2024-05-08 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_in_cents', models.IntegerField()),
                ('description', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ser.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='picture',
            constraint=models.UniqueConstraint(fields=('product', 'url'), name='unique_product_url'),
        ),
    ]
