# Generated by Django 5.0.5 on 2024-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0003_recreate_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.TextField(default='Thomas Shelby'),
        ),
    ]
